CREATE TABLE Plano (
    ID NUMBER(2,0) CONSTRAINT PK_Plano PRIMARY KEY,
    Nome VARCHAR2(50),
    Valor FLOAT
);

CREATE TABLE Personal_Trainer (
    CREF VARCHAR2(11) CONSTRAINT PK_PersonalTreiner PRIMARY KEY,
    Nome VARCHAR2(50) NOT NULL
);

CREATE TABLE Equipamento( 
	Cod INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL, 
	CONSTRAINT PK_Equipamento PRIMARY KEY (Cod) 
);

CREATE TABLE Exercicio( 
	ID INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL, 
	CONSTRAINT PK_Exercicio PRIMARY KEY (ID) 
);

CREATE TABLE Usuario_da_Academia (
    CPF VARCHAR2(11) CONSTRAINT PK_UsuarioAcademia PRIMARY KEY,
    Nome VARCHAR2(50) not null,
    Bairro VARCHAR2(50) not null,
    Rua VARCHAR2(50) not null,
    NCasa VARCHAR2(5) not null,
    Nascimento DATE not null
);

CREATE TABLE Contato (
    CPF VARCHAR2(11),
    Contato VARCHAR2(50) NOT NULL,
    CONSTRAINT FK_Contato_UsuarioC FOREIGN KEY (CPF) REFERENCES Usuario_da_Academia(CPF) ON DELETE CASCADE
);

CREATE TABLE Aluno (
    CPF VARCHAR2(11) CONSTRAINT PK_Aluno PRIMARY KEY,
    ID_Plano NUMBER(2,0) NOT NULL,
    CREF_PT VARCHAR2(11),
    CONSTRAINT FK_CPFA FOREIGN KEY (CPF) REFERENCES Usuario_da_Academia(CPF) ON DELETE CASCADE,
    CONSTRAINT FK_ID_PlanoA FOREIGN KEY (ID_Plano) REFERENCES Plano(ID) ON DELETE CASCADE,
    CONSTRAINT FK_CREF_PTA FOREIGN KEY (CREF_PT) REFERENCES Personal_Trainer(CREF) ON DELETE CASCADE
);

CREATE TABLE Funcionario (
    CPF_func VARCHAR2(11) CONSTRAINT PK_Funcionario PRIMARY KEY,
    Salario INT,
    CPF_chefe VARCHAR2(11),
    CONSTRAINT FK_CPF_funcF FOREIGN KEY (CPF_func) REFERENCES Usuario_da_Academia(CPF) ON DELETE CASCADE,
    CONSTRAINT FK_CPF_chefeF FOREIGN KEY (CPF_chefe) REFERENCES Funcionario(CPF_func) ON DELETE CASCADE
);

CREATE TABLE Instrutor (
    CPF VARCHAR2(11) CONSTRAINT PK_Instrutor PRIMARY KEY,
    CONSTRAINT FK_CPFI FOREIGN KEY (CPF) REFERENCES Funcionario(CPF_func) ON DELETE CASCADE
);

CREATE TABLE Administracao (
    CPF VARCHAR2(11) CONSTRAINT PK_Administracao PRIMARY KEY,
    Funcao VARCHAR2(50) NOT NULL,
    CONSTRAINT FK_CPF_AdministracaoA FOREIGN KEY (CPF) REFERENCES Funcionario(CPF_func) ON DELETE CASCADE
);

CREATE TABLE Avaliacao_Fisica (
    ID INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL CONSTRAINT PK_Avaliacao_Fisica PRIMARY KEY,
    Data DATE NOT NULL,
    CPF_Aluno VARCHAR2(11) NOT NULL,
    CPF_Instrutor VARCHAR2(11) NOT NULL,
    CONSTRAINT FK_CPF_AlunoAF FOREIGN KEY (CPF_Aluno) REFERENCES Aluno(CPF) ON DELETE CASCADE,
    CONSTRAINT FK_CPF_InstrutorAF FOREIGN KEY (CPF_Instrutor) REFERENCES Instrutor(CPF) ON DELETE CASCADE
);

CREATE TABLE Tem (
    CPF_Aluno VARCHAR2(11),
    CPF_Instrutor VARCHAR2(11),
    CONSTRAINT PK_Tem PRIMARY KEY (CPF_Aluno, CPF_Instrutor),
    CONSTRAINT FK_CPF_AlunoT FOREIGN KEY (CPF_Aluno) REFERENCES Aluno(CPF) ON DELETE CASCADE,
    CONSTRAINT FK_CPF_InstrutorT FOREIGN KEY (CPF_Instrutor) REFERENCES Instrutor(CPF) ON DELETE CASCADE
);

CREATE TABLE Ficha_de_treino (
    Cod INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL CONSTRAINT PK_Ficha_de_treino PRIMARY KEY,
    ID_Exercicio NUMBER(10) NOT NULL,
    CPF_Aluno VARCHAR2(11) NOT NULL,
    CPF_Instrutor VARCHAR2(11) NOT NULL,
    CONSTRAINT FK_CPF_Aluno_InstrutorFT FOREIGN KEY (CPF_Aluno, CPF_Instrutor) REFERENCES Tem(CPF_Aluno, CPF_Instrutor) ON DELETE CASCADE,
    CONSTRAINT FK_ID_ExercicioFT FOREIGN KEY (ID_Exercicio) REFERENCES Exercicio(ID) ON DELETE CASCADE
);

CREATE TABLE Acompanhante (
    CPF VARCHAR2(11) CONSTRAINT PK_Acompanhante PRIMARY KEY,
    Nome VARCHAR2(100) NOT NULL,
    CONSTRAINT FK_CPF_Acompanhante FOREIGN KEY (CPF) REFERENCES Aluno(CPF) ON DELETE CASCADE
);

CREATE TABLE ContatoAc (
    CPF VARCHAR2(11),
    Contato VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_ContatoAc PRIMARY KEY (CPF, Contato),
    CONSTRAINT FK_CPF_ContatoAC FOREIGN KEY (CPF) REFERENCES Acompanhante(CPF) ON DELETE CASCADE
);

CREATE TABLE Contratou (
    CPF_Aluno VARCHAR2(11),
    ID_Plano NUMBER(10),
    Data DATE NOT NULL,
    Desconto NUMBER(5, 2),
    CONSTRAINT PK_Contratou PRIMARY KEY (CPF_Aluno, ID_Plano),
    CONSTRAINT FK_CPF_AlunoContr FOREIGN KEY (CPF_Aluno) REFERENCES Aluno(CPF) ON DELETE CASCADE,
    CONSTRAINT FK_ID_PlanoContr FOREIGN KEY (ID_Plano) REFERENCES Plano(ID) ON DELETE CASCADE
);

CREATE TABLE FT_POSSUI_Ex (
    Cod NUMBER(10),
    ID NUMBER(10),
    CONSTRAINT PK_FT_POSSUI_Ex PRIMARY KEY (Cod, ID),
    CONSTRAINT FK_Cod_Ficha_de_treinoFPE FOREIGN KEY (Cod) REFERENCES Ficha_de_treino(Cod) ON DELETE CASCADE,
    CONSTRAINT FK_ID_ExercicioFPE FOREIGN KEY (ID) REFERENCES Exercicio(ID) ON DELETE CASCADE
);

CREATE TABLE Realiza (
    CPF_Aluno VARCHAR2(11),
    COD_Equipamento NUMBER(10),
    ID NUMBER(10),
    Data DATE,
    CONSTRAINT PK_Realiza PRIMARY KEY (CPF_Aluno, COD_Equipamento, ID, Data),
    CONSTRAINT FK_CPF_AlunoR FOREIGN KEY (CPF_Aluno) REFERENCES Aluno(CPF) ON DELETE CASCADE,
    CONSTRAINT FK_COD_EquipamentoR FOREIGN KEY (COD_Equipamento) REFERENCES Equipamento(COD) ON DELETE CASCADE,
    CONSTRAINT FK_ID_ExercicioR FOREIGN KEY (ID) REFERENCES Exercicio(ID) ON DELETE CASCADE
);